title: Ryan Rodenbaugh's personal site
email: rrodenbaugh@gmail.com
description: Ryan Rodenbaugh's Site
url: "ryanrodenbaugh.com"
twitter: ryanrodenbaugh

baseurl: ""
permalink: /:categories/:title:output_ext
markdown: kramdown
plugins:
  - jekyll-feed
